#!/bin/bash

export EDITOR=vim

export PATH=$PATH:/opt/usr/bin

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\][\t]>\n\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w[\t]>\n\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

alias ocaml="rlwrap ocaml"

function unlock_eclipse
{
    locks=$(find $HOME/eclipse/workspaces -type f -name .lock | grep '/\.metadata/\.lock$' | perl -pe 's#\n# #')
    if [ ! -z "$locks" ]; then
        echo $locks
        rm $locks
    fi
}

